plugins:
  - serverless-offline

service: aws-node-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  name:
    handler: handler.name 
    events:
      - http:
          path: /name
          method: post
  currentTime:
    handler: handler.helloworld 
    events:
      - http:
          path: /helloworld
          method: get
# comment définir des param dans l'url ??

          
